# Generated by Django 2.2.5 on 2020-05-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatenslug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoformm',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
