# Generated by Django 2.2.5 on 2020-05-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatenslug', '0002_demoformm_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demoformm',
            options={'ordering': ('-id',)},
        ),
    ]
