# Generated by Django 2.2.5 on 2020-05-17 12:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('updatenslug', '0003_auto_20200515_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoformm',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
