# Generated by Django 2.2.5 on 2020-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatenslug', '0004_demoformm_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoformm',
            name='msg',
            field=models.TextField(unique=True),
        ),
    ]
