# Generated by Django 3.0.6 on 2020-05-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatenslug', '0005_auto_20200517_1816'),
    ]

    operations = [
    ]
